<h1>Basics</h1>

In [2]:
import numpy as np

In [30]:
# if your data is not large you can specify data type as int16
a = np.array([1,2,3], dtype='int32')
a

array([1, 2, 3])

In [18]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [20]:
# Get Dimensions
b.ndim

2

In [22]:
# Get Shape
b.shape

(2, 3)

In [27]:
# Get Type
print(a.dtype)
print(b.dtype)

int16
float64


In [31]:
# Get Size
a.itemsize

4

In [32]:
# Get total size
a.nbytes

12

<h1>Accessing/Changing specific elements, rows, columns,etc</h1>

In [73]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [36]:
#Get a specific element r,c]
a[1,-2]

13

In [37]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [39]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [44]:
a[1,5] =20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


<h3>3d example</h3>

In [57]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [59]:
#Get specific element (work outsb)
b[0,1,1]

4

In [62]:
#Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


<h1>Initializing different types of arrays</h1>

In [63]:
# ALL 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [66]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [68]:
#All 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [70]:
# any other number
np.full((2,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [75]:
#Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [77]:
#Random decimal numbers matrix
np.random.rand(4,2,3)

array([[[0.48070351, 0.0237057 , 0.93358505],
        [0.16969585, 0.187442  , 0.7296088 ]],

       [[0.53042301, 0.39624287, 0.59422635],
        [0.50253549, 0.97650574, 0.75751322]],

       [[0.13458086, 0.61840491, 0.04217643],
        [0.66641781, 0.14054805, 0.05872482]],

       [[0.49962506, 0.4629686 , 0.49892682],
        [0.29377732, 0.03804106, 0.97247203]]])

In [78]:
#Random numbers in shape of a matrix
np.random.random_sample(a.shape)

array([[0.40232905, 0.43722363, 0.81895799, 0.59907838, 0.91479524,
        0.53677644, 0.42101049],
       [0.29260974, 0.87381591, 0.65442655, 0.61875307, 0.53962392,
        0.75490057, 0.0331149 ]])

In [86]:
#Random integer values
np.random.randint(7, size=(3,3))

array([[6, 6, 0],
       [2, 3, 5],
       [5, 6, 4]])

In [87]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [92]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [100]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


<h3>Be careful when copying arrays!!!</h3>

In [102]:
#The way you shouldnt do copying
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [103]:
#the way you should do copying
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


<h1>Mathematics</h1>

In [104]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [105]:
a + 2

array([3, 4, 5, 6])

In [106]:
a -2

array([-1,  0,  1,  2])

In [107]:
a*2

array([2, 4, 6, 8])

In [108]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [110]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [111]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [112]:
#Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

<h1>Linear Algebra</h1>

In [118]:
a = np.full((2,3),1)
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [120]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

<h1>Statistics</h1>

In [121]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
np.min(stats)

1

In [123]:
np.max(stats)

6

In [124]:
np.min(stats, axis = 1)

array([1, 4])

In [127]:
np.min(stats, axis=1)

array([1, 4])

In [131]:
np.sum(stats)

21

<h1>Reorganizing Arrays</h1>

In [134]:
#As long as the new reshaped array has the same number of elements you can reshape your array
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [136]:
#Vertically stacking vector
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [139]:
#Horizontal
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

<h1>Miscellaneous</h1>

In [148]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.]])

In [150]:
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7]
 [  3  42  12  33 766  75   4  55   6   4   3]
 [  1  22  33  11 999  11   2   1  78   0   1]]


<h1>Boolean masking and Advanced indexing</h1>

In [151]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False]])

In [153]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78])

In [158]:
#You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [159]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False])

In [160]:
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False])

In [161]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False]])

In [19]:
0 * np.nan
np.nan == np.nan
np.inf>np.nan
#0 * np.nan
##np.nan == np.nan
#np.inf > np.nan
#np.nan - np.nan
#np.nan in set([np.nan])
#0.3 == 3 * 0.1


False